import type { Metadata } from "next";
import { Providers } from "@/providers/Providers";
import { fonts } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts.gilroy.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
