import type { Metadata } from "next"
import { Providers } from "@/providers/Providers"
import { fonts } from "./fonts/fonts"
import "./globals.css"
import { Header } from "@/components/header/Header"
import { Container } from "@chakra-ui/react"

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={fonts.gilroy.className}>
				<Providers>
					<Header />
					<Container>{children}</Container>
				</Providers>
			</body>
		</html>
	)
}
